set_ifndef(ULTIPARC_TOOLCHAIN_PATH "$ENV{ULTIPARC_TOOLCHAIN_PATH}")
set(       ULTIPARC_TOOLCHAIN_PATH ${ULTIPARC_TOOLCHAIN_PATH} CACHE PATH "")
assert(    ULTIPARC_TOOLCHAIN_PATH "ULTIPARC_TOOLCHAIN_PATH is not set")

set(TOOLCHAIN_HOME ${ULTIPARC_TOOLCHAIN_PATH})

set(COMPILER gcc)

set(CROSS_COMPILE_TARGET mipsisa32-elf)
set(SYSROOT_TARGET       mipsisa32-elf)

set(CROSS_COMPILE ${TOOLCHAIN_HOME}/bin/${CROSS_COMPILE_TARGET}-)
set(SYSROOT_DIR   ${TOOLCHAIN_HOME}/${SYSROOT_TARGET})

list(APPEND TOOLCHAIN_C_FLAGS -mel -mips1 -march=r3000 -msoft-float)
